baseURL = 'https://openstudy.jp/'
languageCode = 'ja-jp'
defaultContentLanguage = "ja"
hasCJKLanguage = true
title = 'OpenStudy'
theme = 'myTheme'
pluralizeListTitles = false
enableGitInfo = true

# Enable syntax highlightning
pygmentsCodeFences = true

# Sass files that always imported
[params]
    basicStyle = ["default", "header", "footer"]

# Enable taxonomies
[taxonomies]
    tag = 'tags'
