baseURL = 'https://openstudy.jp/'
languageCode = 'ja-jp'
defaultContentLanguage = "ja"
hasCJKLanguage = true
title = 'OpenStudy'
theme = 'myTheme'
pluralizeListTitles = false
enableGitInfo = true

# Enable syntax highlightning
pygmentsCodeFences = true


# Enable HTML inside Markdown
[markup.goldmark.renderer]
    unsafe = true

[params]
    # Sass files that always imported
    basicStyle = ["default", "header", "footer", "breadcrumb"]