baseURL = 'https://openstudy.jp/'
languageCode = 'ja-jp'
defaultContentLanguage = "ja"
hasCJKLanguage = true
title = 'OpenStudy'
theme = 'openstudy'
pluralizeListTitles = false
enableGitInfo = true

# Enable syntax highlightning
pygmentsCodeFences = true

# Enable taxonomies
[taxonomies]
    tag = 'tag'

# Create h1 and h2's table of contents
[markup]
    [markup.tableOfContents]
        startLevel = 1
        endLevel = 2
