name: Bug Report
description: OpenStudy.jp のバグを報告する
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        バグの報告に協力していただきありがとうございます！
        
        * 似たようなバグが既に Issues に報告されていないか確認してください。
        * 質問は [Discussions](https://github.com/OpenStudyProject/OpenStudy/discussions) の Q&A カテゴリに書いてください。

  - type: textarea
    attributes:
      label: バグの内容
      description: バグのスクリーンショットも追加してください。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 期待する動作
    validations:
      required: true

  - type: textarea
    attributes:
      label: バグを再現する方法
    validations:
      required: true

  - type: textarea
    attributes:
      label: 動作環境
      description: ブラウザとOSの種類とバージョンは必ず記載してください。
    validations:
      required: true

  - type: textarea
    attributes:
      label: その他に補足したいこと