name: Report bug
description: 不具合を報告する
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        issue を作成していただきありがとうございます！
        
        * 似たような issue が既にないか確認してください。
        * 質問は [Discussions](https://github.com/OpenStudyProject/OpenStudy/discussions) の Q&A カテゴリに書いてください。

  - type: textarea
    attributes:
      label: バグの内容
      description: 必要であればスクリーンショットも追加してください。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 期待する動作
    validations:
      required: true

  - type: textarea
    attributes:
      label: バグを再現する方法
    validations:
      required: true

  - type: textarea
    attributes:
      label: 動作環境
      description: ブラウザとOSの種類とバージョンを記載してください。
    validations:
      required: true

  - type: textarea
    attributes:
      label: その他に補足したいこと