name: Request new feature
description: 新機能の提案や既存の機能の改善提案
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        issue を作成していただきありがとうございます！
        
        * 似たような issue が既にないか確認してください。
        * 質問は [Discussions](https://github.com/OpenStudyProject/OpenStudy/discussions) の Q&A カテゴリに書いてください。

  - type: textarea
    attributes:
      label: 提案の内容
    validations:
      required: true

  - type: textarea
    attributes:
      label: 良くなる点
    validations:
      required: true

  - type: textarea
    attributes:
      label: 悪くなる点
    validations:
      required: true

  - type: textarea
    attributes:
      label: その他に補足したいこと